PR: Improve the typing of the members of the CSSProperties interface
agyemanjp/somatic.js pull request #6
Opened 2022-08-27 12:37 UTC by Sami64

Resolves #4 

Addition of types of the members of CSSProperties interface

2022-09-30 12:11 UTC, agyemanjp requested changes
Why are there these constants in _src/common.ts_: `borderWidthValues`, `cursorKeywords`, `borderStyles`?

You're using them like so:
```
borderBottomWidth?:
    // Keyword values
        | keyof typeof borderWidthValues
        // <Length> values
        | CSSLength;
```

This should be changed to something like this:
```
borderBottomWidth?: (
        | NamedBorderWidth
        | CSSLength;
)
```

The above requires you to define a type like this in _types.ts_, which removes the need for the borderWidthValues delaration in _common.ts:_):

`type NamedBorderWidth = "thin"| "medium"| "thick"`

So please use the same approach to remove the `cursorKeywords` and `borderStyles` declarations in _common.ts_.

Also, in the borderBottomWidth type above, notice how I have removed trivial comments, and wrapped the whole type in parentheses. Please  go through the types and use the same pattern.

2022-11-16 12:06 UTC, agyemanjp requested changes
What are these _types1.ts_ and _types copy.ts_ fies?

2022-11-16 13:18 UTC, Sami64 commented
> 1. What are these _types1.ts_ and _types copy.ts_ files? Please make sure you don't add or remove any file unless we have discussed those as necessary for an issue to be implemented
> 
>     2. Why are there changes to test files? Avoid any changes to files that are not strictly necessary for completing an issue. I see that most of those changes are due to formatting. Please ensure the format setting on your IDE match that of the project, so that there will not be any unnecessary changes.

1. Those were just the referenced files. So I will remove them.
2. The changes in the test files were related to the console logs that were causing the CI errors. So I just commented those out. @agyemanjp

2022-12-23 11:24 UTC, agyemanjp approved these changes

2022-12-30 10:07 UTC, agyemanjp approved these changes

2022-12-30 10:08 UTC, merged